before:
  hooks:
    - go mod download

builds:
  - binary: bcache
    main: bcache.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - id: tgz
    format: tar.gz
    # replacements:
    #     linux: elf
    #     darwin: macho

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Update.*'
